dist: bionic

language:
  - cpp

before_install:
  - sudo apt-get update -qq
  - sudo apt-get install -y qtbase5-dev qtdeclarative5-dev qtquickcontrols2-5-dev
  - sudo apt-get install -y qt5-default qttools5-dev-tools
  - pip install --user cpp-coveralls
  
addons:
    sonarcloud:
        organization: "na6ezh6a"
    token: $SONAR_TOKEN

script:
  - qmake
  - make
  - ./tests/tests

after_success:
  - coveralls --root . -E ".*external.*" -E ".*tests.*" -E "main.cpp" -E "moc_cards.cpp" -E "moc_predefs.h" -E "qrc_qml.cpp"
  - build-wrapper-linux-x86-64 --out-dir bw-output make clean all
  - sonar-scanner

notifications:
  email: false
